assignment:
  target: prod
  outputs:
    dev:
        type: postgres
        host: "{{env_var('DB_HOST')}}"
        port: "{{env_var('DB_PORT')}}"
        user: "{{env_var('DB_USER')}}"
        pass: "{{env_var('DB_PASS')}}"
        dbname: "{{env_var('DB_NAME')}}"
      
    prod:
        type: postgres
        host: "{{env_var('DB_HOST')}}"
        port: 20117
        user: "{{env_var('DB_USER')}}"
        pass: "{{env_var('DB_PASS')}}"
        dbname: "{{env_var('DB_NAME')}}"
        schema: default
